# Tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: Pre-run | Get package facts
      tags: always
      ansible.builtin.package_facts:

# Run roles
- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: kiosk
  tags: kiosk
  become: true
  roles:
    - kiosk

# End of run cleanup and reporting
- hosts: all
  become: true
  tasks:
    - name: Failed provision cleanup
      include_tasks: playbooks/provision_failure.yml
      tags: always
      when:
        - task_failed is defined
        - task_failed | bool