- name: Kiosk | create user
  ansible.builtin.user:
    name: kiosk
    state: present
    comment: "Kiosk"
    password: "{{ kiosk_passwd }}"
    shell: /bin/bash

- name: Kiosk | Install kiosk package
  ansible.builtin.package:
    name: gnome-kiosk-script-session
    state: present

- name: Kiosk | Create directories
  ansible.builtin.file:
    path: '/home/kiosk/{{ item.dir }}'
    state: directory
    owner: kiosk
    group: kiosk
    mode: '{{ item.mode }}'
  with_items:
    - { dir: '.local', mode: '0700' }
    - { dir: '.local/bin', mode: '0755' }

- name: Kiosk | Install session script
  ansible.builtin.template:
    src: gnome-kiosk-script-session.j2
    dest: /home/kiosk/.local/bin/gnome-kiosk-script
    owner: kiosk
    group: kiosk
    mode: '0755'
  notify: restart_firefox

- name: Kiosk | GDM | Set login session
  community.general.ini_file:
    path: /var/lib/AccountsService/users/kiosk
    section: User
    option: Session
    value: gnome-kiosk-script-wayland

- name: Kiosk | GDM | Enable automatic login
  community.general.ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { option: 'AutomaticLoginEnable', value: 'true' }
    - { option: 'AutomaticLogin', value: 'kiosk' }
