- name: Kiosk | create user
  ansible.builtin.user:
    name: kiosk
    state: present
    comment: "Kiosk"
    password: "{{ kiosk_passwd }}"
    shell: /bin/bash

- name: Kiosk | Install kiosk package
  community.general.rpm_ostree_pkg:
    name: gnome-kiosk-script-session
    state: present

- name: Kiosk | Create directories
  ansible.builtin.file:
    path: '/home/kiosk/{{ item.dir }}'
    state: directory
    owner: kiosk
    group: kiosk
    mode: '{{ item.mode }}'
  with_items:
    - { dir: '.local', mode: '0700' }
    - { dir: '.local/bin', mode: '0755' }

- name: Kiosk | Install session script
  ansible.builtin.template:
    src: "gnome-kiosk-script-session-{{ firefox_install }}.j2"
    dest: /home/kiosk/.local/bin/gnome-kiosk-script
    owner: kiosk
    group: kiosk
    mode: '0755'
  notify: restart_firefox

- name: Kiosk | Login configuration
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: 'accountsservice_kiosk', dest: '/var/lib/AccountsService/users/kiosk' }
    - { src: 'accountsservice_tmsadmin', dest: '/var/lib/AccountsService/users/tms_admin'}
    - { src: 'gdm_custom_conf', dest: '/etc/gdm/custom.conf' }

# - name: Kiosk | GDM | Set login session
#   community.general.ini_file:
#     path: /var/lib/AccountsService/users/kiosk
#     section: User
#     option: Session
#     value: gnome-kiosk-script-wayland
#     owner: root
#     group: root
#     mode: '0644'

# - name: Kiosk | GDM | Hide kiosk user in GDM
#   community.general.ini_file:
#     path: /var/lib/AccountsService/users/kiosk
#     section: User
#     option: SystemAccount
#     value: 'true'
#     owner: root
#     group: root
#     mode: '0644'

# - name: Kiosk | GDM | Enable automatic login
#   community.general.ini_file:
#     path: /etc/gdm/custom.conf
#     section: daemon
#     option: '{{ item.option }}'
#     value: '{{ item.value }}'
#     owner: root
#     group: root
#     mode: '0644'
#   with_items:
#     - { option: 'AutomaticLoginEnable', value: 'true' }
#     - { option: 'AutomaticLogin', value: 'kiosk' }

- name: Kiosk | logind | Disable Auto VT
  community.general.ini_file:
    path: /etc/systemd/logind.conf
    section: Login
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { option: 'NAutoVTs', value: '0' }
    - { option: 'ReserveTV', value: '0' }
  when: disable_autovts | bool

- name: Kiosk | Install kill Firefox service unit
  ansible.builtin.copy:
    src: firefox_kill_{{ item }}
    dest: /etc/systemd/system/firefox-kill.{{ item }}
    owner: root
    group: root
    mode: '0640'
  notify: systemd_daemon_reload
  with_items:
    - service

- name: Kiosk | Install kill Firefox timer unit
  ansible.builtin.template:
    src: firefox_kill_{{ item }}.j2
    dest: /etc/systemd/system/firefox-kill.{{ item }}
    owner: root
    group: root
    mode: '0640'
  notify: systemd_daemon_reload
  with_items:
    - timer

- name: Kiosk | Enable kill Firefox on schedule timer
  ansible.builtin.systemd:
    name: firefox-kill.timer
    enabled: true

- name: Kiosk | Firefox policies create directory
  ansible.builtin.file:
    path: /etc/firefox/policies
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: firefox_policies is defined

- name: Kiosk | Set Firefox policies
  ansible.builtin.copy:
    src: "firefox_policies_{{ firefox_policies }}.json"
    dest: /etc/firefox/policies/policies.json
    owner: root
    group: root
    mode: '0644'
  when: firefox_policies is defined
