- name: System setup | Automatic updates | Configure rpm-ostreed
  community.general.ini_file:
    path: /etc/rpm-ostreed.conf
    section: Daemon
    option: AutomaticUpdatePolicy
    value: stage
  notify: rpm-ostree_reload

- name: system setup | automatic updates | Enable a timer for automatic updates
  ansible.builtin.systemd:
    name: "{{ automatic_updates_timer }}"
    enabled: yes
  when: automatic_updates_timer is defined