- name: Firewall | Set default zone
  ansible.builtin.command: firewall-cmd '--set-default-zone={{ firewalld_zone }}'
  register: set_default_zone
  changed_when: '"ZONE_ALREADY_SET" not in set_default_zone.stderr'
